# action.yml
name: 'Update Projen for Latest AWS CDK Release Version'
description: 'Get the latest released version of the AWS CDK filtered by a specific major version and updates the projen rc file accordingly'
inputs:
  major-version:
    description: 'The major version to get the latest release version for'
    required: true
    default: '2'
outputs:
  patch_created:
    description: 'Were changes made?'
    value: ${{ steps.create_patch.outputs.patch_created }}
  build_conclusion:
    description: 'Did the post change build succeed?'
    value: ${{ steps.build.outputs.build_conclusion }}
  previous_version:
    description: 'The version of AWS CDK the projen file contained before this action was run.'
    value: ${{ steps.version_upgrade.outputs.previous_version }}
  new_version:
    description: 'The version of AWS CDK the upgrade script changes the projen file to during this action.'
    value: ${{ steps.version_upgrade.outputs.new_version }}
  patch_name:
    description: 'The name of the patch created if a patch is created'
    value: .repo.patch
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup Node.js
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 14.17.0
    - name: Install dependencies
      run: yarn install --check-files --frozen-lockfile
      shell: bash
    - run: ${{ github.action_path }}/update_cdk_version_in_projen.sh ${{ inputs.major-version }}
      id: version_upgrade
      shell: bash
    - name: Build
      id: build
      shell: bash
      run: npx projen build && echo "::set-output name=build_conclusion::success" || echo
        "::set-output name=build_conclusion::failure"
    - if: steps.build.outputs.build_conclusion == 'success'
      id: create_patch
      name: Find mutations
      shell: bash
      run: >-
        git add .

        git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=patch_created::true"
    - if: steps.create_patch.outputs.patch_created
      name: Upload patch
      uses: actions/upload-artifact@v2
      with:
        name: .repo.patch
        path: .repo.patch
